version: "3"

networks:
  loki:

services:
  loki:
    image: flexberry/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    volumes:
      - LOKIDB:/loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: usr123
      GF_SECURITY_ADMIN_USER: admin
    networks:
      - loki
      
volumes:
  LOKIDB: