version: '3'

networks:
  loki:

services:
  app:
    image: flexberrysamplelogging/app
    links:
      - app-postgres-db:app-postgres-db
    ports:
      - 80:80
    environment:
      - UploadUrl=Uploads
      - BackendRoot=https://localhost
      - DefConnStr=SERVER=app-postgres-db;User ID=flexberryuser;Password=jhv;Port=5432;database=appdb;
    networks:
      - loki

  app-postgres-db:
    image: flexberrysamplelogging/postgre-sql
    volumes:
      - DB:/var/lib/pgsql/data/
    ports:
      - 5432:5432

  loki:
    image: flexberry/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    volumes:
      - LOKIDB:/loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: usr123
      GF_SECURITY_ADMIN_USER: admin
    networks:
      - loki

volumes:
  DB:
  LOKIDB: